### ISSUE TITLE
Wireguard Module

### ISSUE THREAD

**Issue by donmega** [Sanju0910/android_kernel_oneplus_avicii#1]
Hi,

I love your kernel! Would it be possible to add the Wireguard module please?
https://forum.xda-developers.com/t/wireguard-kernel-rom-integration.3711635/

Thank you my friend, keep up the great work!

**Comment by Sanju0910** [comment]
https://github.com/Sanju0910/android_kernel_oneplus_avicii/commit/27b79997a5b8041403b457f4ca7f07e884c62d33

**Comment by donmega** [comment]
Thank you my friend! Do you have a download link for me with the compiled kernel?

**Comment by donmega** [comment]
Working great. I've made a donation. Keep up the great job!
